image:
- Visual Studio 2017
- ubuntu1804

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

clone_depth: 3

build: off

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%
- cmd: set CMAKE_GENERATOR="MinGW Makefiles"
- sh: sudo apt install -yq --no-install-recommends libscalapack-openmpi-dev libopenmpi-dev openmpi-bin

install:
- cmake -B build

- cmake --build build --parallel

test_script:
- cd build
- ctest --parallel --output-on-failure
