name: ci_linux_meson

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**/meson.build"
      - ".github/workflows/ci_linux_meson.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build
      env:
        FC: gfortran-9
        CC: gcc-9
        CXX: g++-9

    - run: meson compile -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Configlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
