name: ci_windows

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"



jobs:

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: cinst -y ninja

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran
        CC: gcc
        CXX: g++
