name: cmake

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 3

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    env:
      CTEST_PARALLEL_LEVEL: 2
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset default
    - run: cmake --build --preset default
    - run: ctest --preset default

  windows:
    runs-on: windows-latest
    env:
      CTEST_PARALLEL_LEVEL: 2
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset default -G "MinGW Makefiles"
    - run: cmake --build --preset default
    - run: ctest --preset default
