name: cmake

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake.yml"


jobs:

  linux-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset=make
    - run: cmake --build build
    - run: ctest --parallel 2 --output-on-failure
      working-directory: build

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset=makewin
    - run: cmake --build build
    - run: ctest --parallel 2 --output-on-failure
      working-directory: build
