name: cmake

env:
  CTEST_NO_TESTS_ACTION: error
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake.yml"


jobs:


  gcc-new:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        fc: [12, 13, 14]
        include:
        - os: macos-latest
          fc: 13

    runs-on: ${{ matrix.os }}

    env:
      FC: gfortran-${{ matrix.fc }}

    steps:
    - uses: actions/checkout@v4

    - name: install Ninja
      if: runner.os == 'Linux'
      run: sudo apt install --no-install-recommends ninja-build

    - name: install Ninja
      if: runner.os == 'macOS'
      run: brew install ninja

    - run: cmake --workflow --preset debug
    - run: cmake --workflow --preset release


  gcc-old:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        fc: [9, 10, 11]

    runs-on: ${{ matrix.os }}

    env:
      FC: gfortran-${{ matrix.fc }}

    steps:
    - uses: actions/checkout@v4

    - name: install Ninja
      run: sudo apt install --no-install-recommends ninja-build

    - run: cmake --workflow --preset debug
    - run: cmake --workflow --preset release


  windows:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v4

    - run: cmake --workflow --preset debug
    - run: cmake --workflow --preset release
