name: meson

on:
  push:
    paths:
      - "**/meson.build"
      - ".github/workflows/meson.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build
    - run: meson compile -C build
    - run: meson test -C build -v

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build
      env:
        FC: gfortran-11
        CC: gcc-11
        CXX: g++-11

    - run: meson compile -C build
    - run: meson test -C build -v

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build
    - run: meson compile -C build
    - run: meson test -C build -v
