name: oneapi-linux

env:
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.c"
      - "**.cpp"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/oneapi-linux.yml"


jobs:

  linux:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: intel
        version: '2023.2'

    - name: Install Ninja
      run: sudo apt-get install ninja-build

    - uses: actions/checkout@v4

    - run: cmake --workflow --preset debug

    - run: cmake --workflow --preset release
